# -*- coding: utf-8 -*-
"""rf_streamlit_2602197305.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DwciniAmAy3AgG091eC-Tuy2grlpjLxp
"""

import streamlit as st
import joblib
import numpy as np

model = joblib.load('mid_modelDeployment_2602197305.pkl')

def main():
  st.title('Mid Term Model Deployment')

  creditScore = st.slider('Credit Score', min_value = 0.0, max_value = 850.0, value = 0.01)
  geography = st.selectbox('Geography', ('0', '1', '2')) # 0 = France, 1 = Germany, 2 = Spain
  gender = st.selectbox('Gender', ('1', '2')) # 1 = male, 2 = female
  age = st.slider('Age', min_value = 0.0, max_value = 100.0, value = 0.01)
  tenure = st.slider('Tenure', min_value = 0.0, max_value = 10.0, value = 0.01)
  balance = st.slider('Balance', min_value = 0.0, max_value = 250898.09, value = 0.01)
  products = st.selectbox('NumOfProducts', ('1', '2', '3', '4'))
  cc = st.selectbox('HasCrCard', ('1', '0'))
  activeMember = st.selectbox('IsActiveMember', ('1', '0'))
  salary = st.slider('EstimatedSalary', min_value = 0.00, max_value = 199992.48, value = 0.01)
  churn = st.selectbox('churn', ('1', '0'))



  if st.button('Make Prediction'):
        features = [creditScore, geography, gender, age, tenure, balance, products, cc, activeMember, salary, churn]
        result = make_prediction(features)
        st.success(f'The prediction is: {result}')

def make_prediction(features):
    input_array = np.array(features).reshape(1, -1)
    prediction = model.predict(input_array)
    return prediction[0]

if __name__ == '__main__':
    main()